# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/alex_/OneDrive/Documents/520_Lab/ECE_Lab11_part1/hardware/bd/webserver_fw/ip/webserver_fw_processing_system7_0_0/webserver_fw_processing_system7_0_0.xci
# IP: The module: 'webserver_fw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alex_/OneDrive/Documents/520_Lab/ECE_Lab11_part1/hardware/bd/webserver_fw/ip/webserver_fw_processing_system7_0_0/webserver_fw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_fw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/alex_/OneDrive/Documents/520_Lab/ECE_Lab11_part1/hardware/bd/webserver_fw/ip/webserver_fw_processing_system7_0_0/webserver_fw_processing_system7_0_0.xci
# IP: The module: 'webserver_fw_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/alex_/OneDrive/Documents/520_Lab/ECE_Lab11_part1/hardware/bd/webserver_fw/ip/webserver_fw_processing_system7_0_0/webserver_fw_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'webserver_fw_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
